export const allNotifications = [
  'Your toll payment of Rs. 150 for the Colombo-Kottawa route has been successfully processed. Thank you for driving with us!',
  'Low Balance Alert! Your account balance is below Rs. 100. Please top up to avoid disruptions during your next journey.',
  'Heavy traffic reported on the Colombo-Kottawa route. Expect delays of up to 20 minutes. Consider alternative routes if possible.',
  'Notice: The Colombo North entry point will be closed for maintenance from 10:00 PM to 4:00 AM. Please plan accordingly.',
  'Your vehicle exceeded the speed limit of 100 km/h on the expressway. For your safety, please adhere to the posted speed limits.',
  'Your toll receipt for the Colombo-Kottawa journey is now available in the app. Tap to view details.',
  'Accident reported ahead on the Kottawa section. Emergency response is on the scene. Please reduce speed and proceed with caution.',
  'Scheduled Maintenance: Sections of the Colombo expressway will be closed for maintenance on Nov 20th, from 2:00 AM to 5:00 AM. Expect possible delays.',
  'Daily Toll Collection: Rs. 1,200,000 collected today from 15,000 vehicles. View detailed report in the dashboard.',
  'Heavy traffic detected at the Colombo entry point. Current wait time is 25 minutes. Consider adjusting toll gate operations.',
  'Maintenance crew successfully completed repairs on the Kottawa exit ramp. All lanes are now open for traffic.',
  'Unusual activity detected: Vehicle with registration ABC-1234 passed through two toll points within an unusually short time. Please investigate.',
  'System Health: All servers are operational, but traffic data synchronization is delayed. Expected resolution in 30 minutes.',
  "Congratulations! Today's revenue target of Rs. 2,000,000 has been achieved. Keep up the great work!",
  'Accident reported near the Colombo tollgate at 2:45 PM. Emergency response team dispatched. Traffic is being diverted.',
  'A new user has registered for expressway toll services. User ID: 56789. Welcome them with a quick intro to the app’s features!',
  'Camera malfunction detected at the Kottawa tollgate. Technicians have been notified and are working on repairs.',
  'High vehicle count detected: Over 10,000 vehicles entered through the Colombo toll today. Monitor for potential congestion.',
];
